### ISSUE TITLE
ExtUtils::Config needed for test and not listed in dependencies

### ISSUE THREAD

**Issue by EGuesnet** [Leont/extutils-installpaths#2]
System: AIX 6.1 on PowerPC 7
Perl 5.30

Hi,

I build and test ExtUtils::InstallPaths. Tests fail because ExtUtils::Config is not found (it is not installed). With ExtUtils::Config, all works.

ExtUtils::Config is not in dependencies of ExtUtils::InstallPaths (not in dist.ini nor in [CPants](https://cpants.cpanauthors.org/release/LEONT/ExtUtils-Config-0.008/prereq)).

Thanks.

**Comment by Leont** [comment]
It is most certainly [listed as a requirement](https://metacpan.org/source/LEONT/ExtUtils-InstallPaths-0.012/META.yml#L25)
